permalink: pretty
# relative_permalinks: true

title: Tessellated Intelligence System Best Practices
tagline:
description: An (eventually) comprehensive spoiler for TIS-100

url: http://www.kk4ead.org
baseurl: /tis-100

author:
  name: George Schaertl (KK4EAD)
  url: http://www.kk4ead.org/
  email: george@schaertl.org

github:
  repo: https://github.com/kk4ead/tis-100
