permalink: pretty
# relative_permalinks: true

title: Tessellated Intelligence System Best Practices
tagline:
description: An (eventually) comprehensive spoiler for TIS-100

url: https://kk4ead.github.io
baseurl: /tis-100

author:
  name: Clara Schaertl Short
  url: https://cshort.io/
  email: clara@cshort.io

github:
  repo: https://github.com/kk4ead/tis-100
