permalink: pretty
# relative_permalinks: true

title: Tessellated Intelligence System Best Practices
tagline:
description: An (eventually) comprehensive spoiler for TIS-100

url: http://tis-100.cshort.io
baseurl: /

author:
  name: Clara Schaertl Short
  url: https://cshort.io/
  email: clara@cshort.io

github:
  repo: https://github.com/kk4ead/tis-100
